[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Master Decision Maker 2.0: Strategies for Making Complex Decisions with Network Science and Complexity Theory"
